services:
  server:
    image: ${DOCKERHUB_USERNAME}/troublepainter-server:latest
    container_name: troublepainter_server
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    networks:
      - app_network
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: troublepainter_redis
    volumes:
      - redis_data:/data
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: ${DOCKERHUB_USERNAME}/troublepainter-nginx:latest
    container_name: troublepainter_nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  redis_data: