name: Nginx CI/CD

on:
  push:
    branches: [develop]
    paths:
      - 'nginx.conf'
      - '.github/workflows/nginx-ci-cd.yml'
      - 'Dockerfile.nginx'

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   

      - name: Docker Setup
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/troublepainter-nginx:latest
          build-args: |
            VITE_API_URL=${{secrets.VITE_API_URL}}
            VITE_SOCKET_URL=${{secrets.VITE_SOCKET_URL}}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: mira
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/mira/web30-stop-troublepainter
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/troublepainter-nginx:latest
            docker compose up -d nginx